#!/usr/bin/env python3
"""High-resolution STL generator for atom spheres (no sockets yet).

Emits a high-detail sphere STL per element using latitude/longitude tessellation.
The sphere radius is derived from diameter_mm (from data/all_elements.csv).
"""
import csv
import math
import os
import struct
from typing import List, Tuple

MASTER_CSV = os.path.join("data", "all_elements.csv")
OUTPUT_DIR = os.path.join("stl", "atoms")

def ensure_dirs():
    os.makedirs(OUTPUT_DIR, exist_ok=True)

def read_master_diameters(path: str) -> List[Tuple[str, float]]:
    items: List[Tuple[str, float]] = []
    with open(path, newline="") as f:
        reader = csv.reader(f)
        header = next(reader, None)  # skip header
        for row in reader:
            if not row:
                continue
            if len(row) < 2:
                continue
            symbol = row[0].strip()
            try:
                diameter = float(row[1].strip())
            except ValueError:
                continue
            items.append((symbol, diameter))
    return items

def vec_sub(a, b):
    return (a[0]-b[0], a[1]-b[1], a[2]-b[2])

def cross(a, b):
    return (a[1]*b[2]-a[2]*b[1], a[2]*b[0]-a[0]*b[2], a[0]*b[1]-a[1]*b[0])

def norm(v):
    l = math.sqrt(v[0]*v[0] + v[1]*v[1] + v[2]*v[2])
    if l == 0:
        return (0.0, 0.0, 0.0)
    return (v[0]/l, v[1]/l, v[2]/l)

def tessellate_sphere(radius: float, lat_steps: int = 70, lon_steps: int = 140):
    tris = []
    for i in range(lat_steps):
        theta1 = math.pi * i / lat_steps
        theta2 = math.pi * (i+1) / lat_steps
        for j in range(lon_steps):
            phi1 = 2*math.pi * j / lon_steps
            phi2 = 2*math.pi * (j+1) / lon_steps
            def v(th, ph):
                return (
                    radius * math.sin(th) * math.cos(ph),
                    radius * math.sin(th) * math.sin(ph),
                    radius * math.cos(th)
                )
            p0 = v(theta1, phi1)
            p1 = v(theta2, phi1)
            p2 = v(theta2, phi2)
            p3 = v(theta1, phi2)
            n1 = norm(cross(vec_sub(p1,p0), vec_sub(p3,p0)))
            n2 = norm(cross(vec_sub(p2,p1), vec_sub(p3,p1)))
            tris.append((n1, p0, p1, p3))
            tris.append((n2, p1, p2, p3))
    return tris

def _point_in_hole(p: Tuple[float, float, float], a: Tuple[float, float, float], u: Tuple[float, float, float], depth: float, r: float) -> bool:
    # check if point p lies within a finite cylinder of radius r along direction u starting at point a,
    # with length depth in the +u direction.
    import math
    # vector from a to p
    w = (p[0]-a[0], p[1]-a[1], p[2]-a[2])
    # projection length along u
    proj = w[0]*u[0] + w[1]*u[1] + w[2]*u[2]
    if proj < 0 or proj > depth:
        return False
    # closest point on the axis to p
    closest = (a[0] + proj*u[0], a[1] + proj*u[1], a[2] + proj*u[2])
    dx, dy, dz = p[0]-closest[0], p[1]-closest[1], p[2]-closest[2]
    d2 = dx*dx + dy*dy + dz*dz
    return d2 <= r*r

def write_binary_stl(filename: str, triangles: List[Tuple[Tuple[float,float,float],Tuple[float,float,float],Tuple[float,float,float],Tuple[float,float,float]]]):
    with open(filename, 'wb') as f:
        header = b"Generated by Molekulbaukasten high-res sphere".ljust(80, b" ")
        f.write(header)
        f.write(struct.pack('<I', len(triangles)))
        for t in triangles:
            n, v1, v2, v3 = t
            f.write(struct.pack('<3f', *n))
            f.write(struct.pack('<3f', *v1))
            f.write(struct.pack('<3f', *v2))
            f.write(struct.pack('<3f', *v3))
            f.write(struct.pack('<H', 0))

def main():
    ensure_dirs()
    items = read_master_diameters(MASTER_CSV)
    for symbol, diam in items:
        radius = diam / 2.0
        tris = tessellate_sphere(radius, lat_steps=70, lon_steps=140)
        # Holes: six bores along +/- X/Y/Z directions
        holes = [
            ((radius, 0.0, 0.0), (-1.0, 0.0, 0.0)),  # +X into sphere
            ((-radius, 0.0, 0.0), (1.0, 0.0, 0.0)),  # -X into sphere
            ((0.0, radius, 0.0), (0.0, -1.0, 0.0)),  # +Y into sphere
            ((0.0, -radius, 0.0), (0.0, 1.0, 0.0)),  # -Y into sphere
            ((0.0, 0.0, radius), (0.0, 0.0, -1.0)),  # +Z into sphere
            ((0.0, 0.0, -radius), (0.0, 0.0, 1.0)),  # -Z into sphere
        ]
        final = []
        for tri in tris:
            n, p0, p1, p2 = tri
            centroid = ((p0[0]+p1[0]+p2[0])/3.0, (p0[1]+p1[1]+p2[1])/3.0, (p0[2]+p1[2]+p2[2])/3.0)
            blocked = False
            for a, u in holes:
                if _point_in_hole(centroid, a, u, depth=4.0, r=4.0):
                    blocked = True
                    break
            if not blocked:
                final.append((n, p0, p1, p2))
        path = os.path.join(OUTPUT_DIR, f"{symbol}.stl")
        write_binary_stl(path, final)
        print(f"Generated {path} with {len(final)} triangles after holes.")
    print("Done: high-resolution atom STLs generated under stl/atoms/")

if __name__ == "__main__":
    main()
